config/routes.rb
Rails.application.routes.draw do
  get 'activity/index'
  get 'activity/new'
  get 'activity/create'
  get 'activity/destroy'
  get 'activity/edit'
  get 'activity/show'
  get 'activity/index'

  get 'role/index'
  get 'role/new'
  get 'role/create'
  get 'role/destroy'
  get 'role/edit'
  get 'role/show'

  get 'task/index'
  get 'task/new'
  get 'task/create'
  get 'task/destroy'
  get 'task/edit'
  get 'task/show'

  get 'projects/index'#done
  get 'projects/new'#done
  get 'projects/destroy'#done - unused
  get 'projects/edit'#done
  get 'projects/show'#done

  get 'clients/index'#done
  get 'clients/new' #done
  get 'clients/create' #done - unused
  get 'clients/destroy'#done
  get 'clients/edit'#done
  get 'clients/show'#done



  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  resources :clients
  resources :projects
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :manageable, polymorphic: true
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects
end

app/models/permitted_params.rb
class PermittedParams < Struct.new(:params, :current_user)
  def user
    params.require(:user).permit(*user_attributes)
  end
  def user_attributes
    if current_user.admin?
      [:name, :email,:password, :password_confirmation, :role ,:admin]
    else
      [ :name, :email, :remember_me,:password, :password_confirmation, ]
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :client
	has_many :tasks, dependent: :destroy
	accepts_nested_attributes_for :tasks, reject_if: proc { |a| a['name'].blank? }, :allow_destroy => true
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	has_many :activities, as: :manageable
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
	has_many :activities, as: :manageable
	enum role: [:user, :project_manager, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
	self.role ||= :user
	end

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def show
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def new_user
		#@user = Users.new
	end
	def create_user
		@user = User.create(user_params)
		if @user.save
		#success
		else
		#error
		#end
	end
	def user_params
		params.requiere(:user).permit(:name,:email,:password,:password_confirmation)
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients=Client.all
  end
 
  def new
    @client=Client.new
  end

  def create
    @client=Client.create(client_params)
    if @client 
      redirect_to root_path, :notice=>"client "+@client.name+" created!"
    else
    end
  end

  def update
    @client=Client.find(params[:id])
    if @client.update_attributes(client_params)
      redirect_to client_path, :notice => "Funcionó"
    else
      #render "create"
    end
  end

  def destroy
    @client=Client.find(params[:id])
    @client.destroy
    redirect_to client_path, :notice=>"Cliente borrado"
  end

  def edit
    @client=Client.find(params[:id])
  end

  def show
    @client=Client.find(params[:id])
  end
  def client_params
    params.require(:client).permit(:name)
  end
end

app/controllers/role_controller.rb
class RoleController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def show
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => [:index, :show, :new, :create]

  def index
    @users = User.all
  end

  def new
    @user=User.create()
  end

  def create

  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end
  def user_params
    params.require(:user).permit(:role, :name, :email, :password, :password_confirmation)
  end

end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/admins/create_user.html.erb
<h1>Admins#create_user</h1>
<p>Find me in app/views/admins/create_user.html.erb</p>

app/views/admins/new_user.html.erb
<h1>Admins#new_user</h1>
<p>Find me in app/views/admins/new_user.html.erb</p>
<%= form_for(@user, :url => admins_create_user_path) do |f| %>
  <div class="form-group">
		<%= f.label :name %>
		<%= f.name_field :name, :autofocus => true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :email %>
		<%= f.email_field :email, :autofocus => true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>
	</div>
		<%= f.submit 'Create User.', :class => 'button right' %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Editar Cuenta', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <% if current_user.admin? %>
  	<li><%= link_to 'Añadir Usuario', new_user_path %></li>
  <%end%>
  <li><%= link_to 'Añadir Cliente', new_client_path %></li>
  <li><%= link_to 'Añadir Proyecto', new_project_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gestor Proyectos Kunder" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gestor Proyectos Kunder" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>